fixes:
  - "chimerax/add_charge/::src/bundles/add_charge/src/"
  - "chimerax/addh/::src/bundles/addh/src/"
  - "chimerax/alignment_algs/::src/bundles/alignment_algs/src/"
  - "chimerax/alignment_headers/::src/bundles/alignment_headers/src/"
  - "chimerax/alphafold/::src/bundles/alphafold/src/"
  - "chimerax/altloc_explorer/::src/bundles/altloc_explorer/src/"
  - "chimerax/amber_info/::src/bundles/amber_info/src/"
  - "chimerax/animations/::src/bundles/animations/src/"
  - "chimerax/arrays/::src/bundles/arrays/src/"
  - "chimerax/atom_search/::src/bundles/atom_search/src/"
  - "chimerax/atomic/::src/bundles/atomic/src/"
  - "chimerax/atomic_lib/::src/bundles/atomic_lib/src/"
  - "chimerax/axes_planes/::src/bundles/axes_planes/src/"
  - "chimerax/basic_actions/::src/bundles/basic_actions/src/"
  - "chimerax/bild/::src/bundles/bild/src/"
  - "chimerax/blastprotein/::src/bundles/blastprotein/src/"
  - "chimerax/bogus/::src/bundles/bogus/src/"
  - "chimerax/bond_rot/::src/bundles/bond_rot/src/"
  - "chimerax/bug_reporter/::src/bundles/bug_reporter/src/"
  - "chimerax/build_structure/::src/bundles/build_structure/src/"
  - "chimerax/bumps/::src/bundles/bumps/src/"
  - "chimerax/bundle_builder/::src/bundles/bundle_builder/src/"
  - "chimerax/buttons/::src/bundles/buttons/src/"
  - "chimerax/cage_builder/::src/bundles/cage_builder/src/"
  - "chimerax/cellpack/::src/bundles/cellpack/src/"
  - "chimerax/centroids/::src/bundles/centroids/src/"
  - "chimerax/change_chains/::src/bundles/change_chains/src/"
  - "chimerax/check_waters/::src/bundles/check_waters/src/"
  - "chimerax/chem_group/::src/bundles/chem_group/src/"
  - "chimerax/clashes/::src/bundles/clashes/src/"
  - "chimerax/cmd_line/::src/bundles/cmd_line/src/"
  - "chimerax/color_actions/::src/bundles/color_actions/src/"
  - "chimerax/color_globe/::src/bundles/color_globe/src/"
  - "chimerax/color_key/::src/bundles/color_key/src/"
  - "chimerax/connect_structure/::src/bundles/connect_structure/src/"
  - "chimerax/core/::src/bundles/core/src/"
  - "chimerax/core_formats/::src/bundles/core_formats/src/"
  - "chimerax/coulombic/::src/bundles/coulombic/src/"
  - "chimerax/crosslinks/::src/bundles/crosslinks/src/"
  - "chimerax/crystal/::src/bundles/crystal/src/"
  - "chimerax/crystal_contacts/::src/bundles/crystal_contacts/src/"
  - "chimerax/data_formats/::src/bundles/data_formats/src/"
  - "chimerax/deep_mutational_scan/::src/bundles/deep_mutational_scan/src/"
  - "chimerax/dicom/::src/bundles/dicom/src/"
  - "chimerax/diffplot/::src/bundles/diffplot/src/"
  - "chimerax/dist_monitor/::src/bundles/dist_monitor/src/"
  - "chimerax/dock_prep/::src/bundles/dock_prep/src/"
  - "chimerax/dssp/::src/bundles/dssp/src/"
  - "chimerax/emdb_sff/::src/bundles/emdb_sff/src/"
  - "chimerax/esmfold/::src/bundles/esmfold/src/"
  - "chimerax/exp_cmd/::src/bundles/exp_cmd/src/"
  - "chimerax/file_history/::src/bundles/file_history/src/"
  - "chimerax/foldseek/::src/bundles/foldseek/src/"
  - "chimerax/function_key/::src/bundles/function_key/src/"
  - "chimerax/geometry/::src/bundles/geometry/src/"
  - "chimerax/gltf/::src/bundles/gltf/src/"
  - "chimerax/graphics/::src/bundles/graphics/src/"
  - "chimerax/hbonds/::src/bundles/hbonds/src/"
  - "chimerax/help_viewer/::src/bundles/help_viewer/src/"
  - "chimerax/hkcage/::src/bundles/hkcage/src/"
  - "chimerax/ihm/::src/bundles/ihm/src/"
  - "chimerax/image_formats/::src/bundles/image_formats/src/"
  - "chimerax/imod/::src/bundles/imod/src/"
  - "chimerax/interfaces/::src/bundles/interfaces/src/"
  - "chimerax/io/::src/bundles/io/src/"
  - "chimerax/items_inspection/::src/bundles/items_inspection/src/"
  - "chimerax/iupac/::src/bundles/iupac/src/"
  - "chimerax/label/::src/bundles/label/src/"
  - "chimerax/leap_motion/::src/bundles/leap_motion/src/"
  - "chimerax/lighting_gui/::src/bundles/lighting_gui/src/"
  - "chimerax/linux_support/::src/bundles/linux_support/src/"
  - "chimerax/list_info/::src/bundles/list_info/src/"
  - "chimerax/log/::src/bundles/log/src/"
  - "chimerax/looking_glass/::src/bundles/looking_glass/src/"
  - "chimerax/maestro/::src/bundles/maestro/src/"
  - "chimerax/map/::src/bundles/map/src/"
  - "chimerax/map_data/::src/bundles/map_data/src/"
  - "chimerax/map_eraser/::src/bundles/map_eraser/src/"
  - "chimerax/map_filter/::src/bundles/map_filter/src/"
  - "chimerax/map_fit/::src/bundles/map_fit/src/"
  - "chimerax/map_series/::src/bundles/map_series/src/"
  - "chimerax/markers/::src/bundles/markers/src/"
  - "chimerax/mask/::src/bundles/mask/src/"
  - "chimerax/match_maker/::src/bundles/match_maker/src/"
  - "chimerax/mcopy/::src/bundles/mcopy/src/"
  - "chimerax/md_crds/::src/bundles/md_crds/src/"
  - "chimerax/medical_imaging/::src/bundles/medical_imaging/src/"
  - "chimerax/medical_toolbar/::src/bundles/medical_toolbar/src/"
  - "chimerax/meeting/::src/bundles/meeting/src/"
  - "chimerax/mlp/::src/bundles/mlp/src/"
  - "chimerax/mmcif/::src/bundles/mmcif/src/"
  - "chimerax/mmtf/::src/bundles/mmtf/src/"
  - "chimerax/model_panel/::src/bundles/model_panel/src/"
  - "chimerax/model_series/::src/bundles/model_series/src/"
  - "chimerax/modeller/::src/bundles/modeller/src/"
  - "chimerax/mol2/::src/bundles/mol2/src/"
  - "chimerax/mole/::src/bundles/mole/src/"
  - "chimerax/morph/::src/bundles/morph/src/"
  - "chimerax/mouse_modes/::src/bundles/mouse_modes/src/"
  - "chimerax/movie/::src/bundles/movie/src/"
  - "chimerax/neuron/::src/bundles/neuron/src/"
  - "chimerax/nifti/::src/bundles/nifti/src/"
  - "chimerax/nih_presets/::src/bundles/nih_presets/src/"
  - "chimerax/nmrstar/::src/bundles/nmrstar/src/"
  - "chimerax/nrrd/::src/bundles/nrrd/src/"
  - "chimerax/nucleotides/::src/bundles/nucleotides/src/"
  - "chimerax/open_command/::src/bundles/open_command/src/"
  - "chimerax/orthopick/::src/bundles/orthopick/src/"
  - "chimerax/pdb/::src/bundles/pdb/src/"
  - "chimerax/pdb_bio/::src/bundles/pdb_bio/src/"
  - "chimerax/pdb_images/::src/bundles/pdb_images/src/"
  - "chimerax/pdb_lib/::src/bundles/pdb_lib/src/"
  - "chimerax/pdb_matrices/::src/bundles/pdb_matrices/src/"
  - "chimerax/phenix_ui/::src/bundles/phenix_ui/src/"
  - "chimerax/pick_blobs/::src/bundles/pick_blobs/src/"
  - "chimerax/positions/::src/bundles/positions/src/"
  - "chimerax/preset_mgr/::src/bundles/preset_mgr/src/"
  - "chimerax/profile_grids/::src/bundles/profile_grids/src/"
  - "chimerax/pubchem/::src/bundles/pubchem/src/"
  - "chimerax/read_pbonds/::src/bundles/read_pbonds/src/"
  - "chimerax/realsense/::src/bundles/realsense/src/"
  - "chimerax/registration/::src/bundles/registration/src/"
  - "chimerax/remote_control/::src/bundles/remote_control/src/"
  - "chimerax/render_by_attr/::src/bundles/render_by_attr/src/"
  - "chimerax/renumber_residues/::src/bundles/renumber_residues/src/"
  - "chimerax/residue_fit/::src/bundles/residue_fit/src/"
  - "chimerax/rest_server/::src/bundles/rest_server/src/"
  - "chimerax/rna_layout/::src/bundles/rna_layout/src/"
  #- "chimerax/rotamer_libs/::src/bundles/rotamer_libs/src/"
  #- "chimerax/rotamers/::src/bundles/rotamers/src/"
  - "chimerax/save_command/::src/bundles/save_command/src/"
  - "chimerax/scenes/::src/bundles/scenes/src/"
  - "chimerax/scheme_mgr/::src/bundles/scheme_mgr/src/"
  - "chimerax/sdf/::src/bundles/sdf/src/"
  #- "chimerax/segger/::src/bundles/segger/src/"
  - "chimerax/segment/::src/bundles/segment/src/"
  - "chimerax/segmentations/::src/bundles/segmentations/src/"
  - "chimerax/sel_inspector/::src/bundles/sel_inspector/src/"
  - "chimerax/seq_view/::src/bundles/seq_view/src/"
  - "chimerax/seqalign/::src/bundles/seqalign/src/"
  - "chimerax/shape/::src/bundles/shape/src/"
  - "chimerax/shell/::src/bundles/shell/src/"
  - "chimerax/shortcuts/::src/bundles/shortcuts/src/"
  - "chimerax/show_sequences/::src/bundles/show_sequences/src/"
  - "chimerax/sideview/::src/bundles/sideview/src/"
  - "chimerax/signal_viewer/::src/bundles/signal_viewer/src/"
  - "chimerax/sim_matrices/::src/bundles/sim_matrices/src/"
  - "chimerax/smiles/::src/bundles/smiles/src/"
  - "chimerax/smooth_lines/::src/bundles/smooth_lines/src/"
  - "chimerax/spacenavigator/::src/bundles/spacenavigator/src/"
  - "chimerax/speech/::src/bundles/speech/src/"
  - "chimerax/std_commands/::src/bundles/std_commands/src/"
  - "chimerax/stl/::src/bundles/stl/src/"
  - "chimerax/storm/::src/bundles/storm/src/"
  - "chimerax/struct_measure/::src/bundles/struct_measure/src/"
  - "chimerax/struts/::src/bundles/struts/src/"
  - "chimerax/surface/::src/bundles/surface/src/"
  - "chimerax/swap_res/::src/bundles/swap_res/src/"
  - "chimerax/swapaa/::src/bundles/swapaa/src/"
  - "chimerax/tape_measure/::src/bundles/tape_measure/src/"
  - "chimerax/task_manager/::src/bundles/task_manager/src/"
  - "chimerax/test/::src/bundles/test/src/"
  - "chimerax/to_quest/::src/bundles/to_quest/src/"
  - "chimerax/toolbar/::src/bundles/toolbar/src/"
  - "chimerax/toolshed_utils/::src/bundles/toolshed_utils/src/"
  - "chimerax/topography/::src/bundles/topography/src/"
  - "chimerax/tug/::src/bundles/tug/src/"
  - "chimerax/tug_ligands/::src/bundles/tug_ligands/src/"
  - "chimerax/ui/::src/bundles/ui/src/"
  - "chimerax/uniprot/::src/bundles/uniprot/src/"
  - "chimerax/unit_cell/::src/bundles/unit_cell/src/"
  - "chimerax/viewdockx/::src/bundles/viewdockx/src/"
  - "chimerax/viperdb/::src/bundles/viperdb/src/"
  - "chimerax/vive/::src/bundles/vive/src/"
  - "chimerax/volume_menu/::src/bundles/volume_menu/src/"
  - "chimerax/vrml/::src/bundles/vrml/src/"
  - "chimerax/vtk/::src/bundles/vtk/src/"
  - "chimerax/wavefront_obj/::src/bundles/wavefront_obj/src/"
  - "chimerax/webcam/::src/bundles/webcam/src/"
  - "chimerax/webservices/::src/bundles/webservices/src/"
  - "chimerax/zone/::src/bundles/zone/src/"
